apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-1-control-app
  namespace: argocd
# finalizer disabled, because otherwise everything under this Application would be deleted as well, if this Application is deleted by accident
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argo-project
  source:
    path: argocd/
    repoURL: ssh://repo
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true