@startuml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/tools/k8s.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.0.0
!includeurl ICONURL/devicons/git.puml
!includeurl ICONURL/font-awesome-5/sync.puml
!includeurl ICONURL/font-awesome-5/globe.puml

!define CLOUDOGU_BLUE #23a3dd
!define COLOR_ABOVE_TRANSPARENT_BACKGROUND WHITE

skinparam backgroundcolor TRANSPARENT
    
together {
    rectangle "<$git>\nCloud Infra\nRepo" as configRepo
}

together {
    rectangle "<$k8s>\nManagement Cluster" as mgmt {
        rectangle "<$sync>\nGitOps\noperator" as gitops
        rectangle "<$k8s>\nAPI-Server" as apiServer
        rectangle "<$globe>\nInfra operator" as infra
    }
}

together {
    collections "<$k8s>\nTarget Clusters" as t1
    cloud "Cloud providers" as t3
}

configRepo <- gitops
apiServer -[hidden]> infra
gitops -> apiServer : apply resources
infra -> apiServer : watch
infra --> t1
infra --> t3


skinparam arrow {
    Color CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam rectangle {
    BackgroundColor WHITE
    BorderColor #16688d
    FontColor CLOUDOGU_BLUE
}

skinparam cloud {
    BackgroundColor WHITE
    BorderColor #16688d
    FontColor CLOUDOGU_BLUE
}

skinparam collections {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

@enduml