apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-nginx-helm-production
  namespace: argocd
spec:
  destination:
    namespace: argocd-production
    server: https://kubernetes.default.svc
  project: exercises
  source:
    path: production/exercise-nginx-helm
    repoURL: https:/repo
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
