@startuml

!includeurl https://raw.githubusercontent.com/michiel/plantuml-kubernetes-sprites/master/resource/k8s-sprites-unlabeled-25pct.iuml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/docker.puml
!includeurl ICONURL/devicons/git.puml
!includeurl ICONURL/font-awesome-5/jenkins.puml
!includeurl ICONURL/font-awesome-5/sync.puml
!includeurl ICONURL/font-awesome-5/box.puml
!includeurl ICONURL/material/computer.puml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/tools/k8s.puml
!includeurl CLOUDOGUURL/dogus/scm.puml

!define CLOUDOGU_BLUE #23a3dd

!define COLOR_ABOVE_TRANSPARENT_BACKGROUND WHITE

skinparam backgroundcolor TRANSPARENT
skinparam actorStyle awesome


node "Your Host" as host <<$computer>> #ffffff {

    actor " " as dev
    
    together {
        rectangle "<$docker>\nDocker Daemon" as docker
        
        rectangle "<$k8s>\nK3d Container" as k8s {
            
            together {
                rectangle "<$scm>\nSCM-Manager" as scmm {
                    collections "<$git>\nApp Repos" as appRepo
                    collections "<$git>\nGitOps Repos" as configRepo
                }
                collections "<$sync>\nArgoCD" as gitops
                collections "<$deploy>\nStaging (6.)\n+ Production (7.)" as staging
            }
            
            rectangle "<$box>\nRegistry" as registry
            rectangle "<$jenkins>\nJenkins" as jenkins
            
        }
    }
}

docker -> k8s : run
dev --> appRepo #line:black;text:black : 1. push  
dev --> staging : 7. review  
dev --> configRepo : 8. accept PR  
appRepo -[hidden]> configRepo
appRepo <-- jenkins : 2. pull
configRepo <-- jenkins : 4. push\nIaC\n + Create PR
jenkins -> registry : 3. push\nimage


configRepo <- gitops : 5. pull
registry -[hidden]> gitops

gitops -> staging : deploy

skinparam arrow {
  Color BLACK
}

skinparam node {
  BorderColor CLOUDOGU_BLUE
}

skinparam actor {
  BackgroundColor #23a3dd
  BorderColor #16688d
  FontColor #000000
}

skinparam actor {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
}

skinparam rectangle {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam collections {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam interface {
    BackgroundColor WHITE
    BorderColor #16688d
}

skinparam note {
    BackgroundColor WHITE
    BorderColor #16688d
}


@enduml