@startuml

' This is only the basis for gitops-tools-maturity.svg
' Which was modified manually (as SVG), because plantuml wasn't capable of realizing the ideas

!includeurl https://raw.githubusercontent.com/michiel/plantuml-kubernetes-sprites/master/resource/k8s-sprites-unlabeled-25pct.iuml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/tools/k8s.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/docker.puml
!includeurl ICONURL/material/computer.puml
!includeurl ICONURL/devicons/git.puml
!includeurl ICONURL/font-awesome-5/globe.puml
!includeurl ICONURL/font-awesome-5/user.puml
!includeurl ICONURL/font-awesome-5/hdd.puml
!includeurl ICONURL/font-awesome-5/server.puml
!includeurl ICONURL/font-awesome-5/tools.puml

!define CLOUDOGU_BLUE #23a3dd
!define COLOR_ABOVE_TRANSPARENT_BACKGROUND BLACK

skinparam backgroundcolor TRANSPARENT

together {
    rectangle "<$git>\n K8s Resources" as k8sAppOpsRepo
    
    rectangle "<$git>\n K8s Clusters" as k8sClustersRepo
    
    rectangle "<$git>\n Cloud Infra" as infraRepo
    
    rectangle "<$git>\n Physical Layer" as hwRepo
    
    k8sAppOpsRepo --[hidden]> k8sClustersRepo
    k8sClustersRepo --[hidden]> infraRepo
    infraRepo --[hidden]> hwRepo
}

rectangle "1 " <<Hidden>> as p3 
rectangle "2 " <<Hidden>> as p2
p2 -> p3: GitOps tool maturity
p2 -[hidden]> k8sAppOpsRepo
p3 -[hidden]> hwRepo
rectangle "<$tools>\nGitOps tool\nmaturity" as infraRepo


node "Physical Layer" as hardware <<$computer>> #ffffff {
    cloud "Cloud Infra" as cloud {
        rectangle "<$k8s>\nCluster" <<NoBackground>> as cluster1 {
            rectangle "<$pod>\nPods" as pods
            rectangle "<$svc>\nServices" as svcs
            rectangle "..." as k8sEtc
            pods -[hidden]> svcs
            svcs -[hidden]> k8sEtc
        }
        rectangle "<$user>\nIAM" as iam
        rectangle "<$globe>\nDNS" as dns
        rectangle "..." as cloudEtc
        cluster1 --[hidden]> iam
        iam -[hidden]> dns
        dns -[hidden]> cloudEtc
    }
    
    rectangle  "<$server>\nServers" as servers
    rectangle "<$hdd>\nSwitches" as switches
    rectangle "..." as hwEtc
    cloud ---[hidden]> servers
    servers -[hidden]> switches
    switches -[hidden]> hwEtc
}

'k8sAppOpsRepo <- pods
'k8sClustersRepo <- cluster1
'infraRepo <- cloud
hwRepo <- hardware

skinparam rectangle<<Hidden>> {
  textColor White
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

skinparam rectangle<<NoBorder>> {
    BorderColor transparent
    borderColor Transparent
    backgroundColor Transparent
    stereotypeFontColor Transparent
}

skinparam arrow {
    Color CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam actor {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor COLOR_ABOVE_TRANSPARENT_BACKGROUND
}

skinparam rectangle {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor WHITE
}
skinparam rectangle<<NoBackground>> {
    BackgroundColor Transparent
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam cloud {
    BackgroundColor WHITE
    BorderColor CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}

skinparam node {
  BorderColor CLOUDOGU_BLUE
  FontColor CLOUDOGU_BLUE
}

skinparam note {
    BackgroundColor WHITE
    BorderColor #16688d
}

@enduml