@startuml

!define CLOUDOGU_BLUE #23a3dd
!define CLOUDOGU_GRAY #878787
!define CLOUDOGU_GREEN #b8cd08
!define CLOUDOGU_TURQOUISE #67c1be

!define COLOR_ABOVE_TRANSPARENT_BACKGROUND BLACK

skinparam backgroundcolor WHITE
'skinparam backgroundcolor TRANSPARENT


rectangle "ArgoCD/Flux" as argocd

together {
    rectangle "Prometheus" as prometheus
    rectangle "Grafana" as grafana
    rectangle "Mailserver, Chat, etc" as msg
}
rectangle "Alertmanager" as alertmanager

argocd <-- prometheus : scrape
prometheus <-- grafana: Option 2:\nquery metrics
alertmanager <- prometheus : Option 1:\nsend Alert
grafana --> msg : send alert
alertmanager -> msg : send alert



skinparam arrow {
    Color COLOR_ABOVE_TRANSPARENT_BACKGROUND
    FontColor COLOR_ABOVE_TRANSPARENT_BACKGROUND
}

skinparam actor {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor COLOR_ABOVE_TRANSPARENT_BACKGROUND
}

skinparam rectangle {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor WHITE
}

skinparam rectangle<<Git>> {
    BackgroundColor CLOUDOGU_GREEN
    BorderColor CLOUDOGU_GRAY
    FontColor WHITE
    stereotypeFontColor Transparent
}

skinparam interface {
    BackgroundColor WHITE
    BorderColor #16688d
}

skinparam note {
    BackgroundColor TRANSPARENT
    FontColor COLOR_ABOVE_TRANSPARENT_BACKGROUND
    BorderColor #16688d
    BorderThickness 2
}

skinparam legend {
    BackgroundColor WHITE
    BorderColor #16688d
}

@enduml

