@startuml

!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master
!includeurl CLOUDOGUURL/tools/k8s.puml

!define CLOUDOGU_BLUE #23a3dd
!define COLOR_ABOVE_TRANSPARENT_BACKGROUND WHITE

together {
    rectangle "<$k8s>\nManagement Cluster" as mgmt
    rectangle " " as mgmt2
    hide mgmt2
}

together {
    rectangle "<$k8s>\nTarget Cluster" as t1
    rectangle "<$k8s>\nTarget Cluster" as t2
    rectangle "<$k8s>\nTarget Cluster" as t3
}

mgmt -[hidden]-> mgmt2
mgmt -> t1
mgmt -> t2
mgmt -> t3

t1 -[hidden]-> t2
t2 -[hidden]-> t3


skinparam arrow {
    Color CLOUDOGU_BLUE
    FontColor CLOUDOGU_BLUE
}


skinparam rectangle {
    BackgroundColor CLOUDOGU_BLUE
    BorderColor #16688d
    FontColor WHITE
}

@enduml